# Generated by Django 5.1.3 on 2024-12-04 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XGBoostModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instrument_key', models.CharField(max_length=50)),
                ('interval', models.CharField(choices=[('1M', '1 Minute'), ('15M', '15 Minutes'), ('1H', '1 Hour'), ('3H', '3 Hours'), ('1D', '1 Day')], max_length=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('prediction_step', models.PositiveIntegerField()),
                ('train_split', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('eta', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('subsample', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('colsample_bytree', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('seed', models.IntegerField()),
                ('max_depth', models.PositiveIntegerField()),
                ('num_boost_round', models.PositiveIntegerField()),
                ('early_stopping_rounds', models.PositiveIntegerField()),
                ('verbose_eval', models.BooleanField(default=False)),
                ('lagging_count', models.PositiveIntegerField()),
                ('model_file', models.CharField(blank=True, max_length=255, null=True)),
                ('model_structure_file', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_features', models.JSONField(default=dict)),
                ('training_mse', models.FloatField(blank=True, null=True)),
                ('training_mae', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
